In [2]:
import sys
sys.path.append('C:/Users/DVOS/Documents/Github/cmglib/cmglib')

In [3]:
import numpy as np
from builder import Builder

In [38]:
# nx, ny, nz = 4, 2, 1
nx, ny, nz = 10, 10, 10
model = Builder(nx, ny, nz)

In [ ]:
# with open('Arquivos/Fluxo_COORD.inc', 'r', encoding='UTF-8') as entrada:
#     prop_name = entrada.readline()
#     coord = model.ler_propriedade(entrada)
# coord

In [40]:
coord = model.ler_coord('Arquivos/Fluxo_COORD.inc')


Lendo arquivo: Arquivos/Fluxo_COORD.inc


Loading:   0%|          | 0/726 [00:00<?, ?it/s]

Loading: 100%|██████████| 726/726 [00:00<00:00, 727614.03it/s]


In [16]:
e = coord.flatten()[0::3]
x0 = np.reshape(e[0::2], (5, 3), order='F')
x0

array([[  0.,   0.,   0.],
       [100., 100., 100.],
       [200., 200., 200.],
       [300., 300., 300.],
       [400., 400., 400.]])

In [17]:
n = coord.flatten()[1::3]
x1 = np.reshape(n[0::2], (5, 3), order='F')
x1

array([[  0., 200., 400.],
       [  0., 200., 400.],
       [  0., 200., 400.],
       [  0., 200., 400.],
       [  0., 200., 400.]])

In [41]:
ztop, zbase = model.ler_zcorn('Arquivos/Fluxo_ZCORN.inc')


Lendo arquivo Arquivos/Fluxo_ZCORN.inc...


Loading: 100%|██████████| 8000/8000 [00:00<00:00, 8071790.23it/s]


In [38]:
ztop.shape

(32,)

In [39]:
zbase.shape

(32,)

In [42]:
model.retornar_xyz(coord, ztop, zbase)

In [25]:
model.coor['x']

array([  0., 100., 100., 200., 200., 300., 300., 400.,   0., 100., 100.,
       200., 200., 300., 300., 400.,   0., 100., 100., 200., 200., 300.,
       300., 400.,   0., 100., 100., 200., 200., 300., 300., 400.,   0.,
       100., 100., 200., 200., 300., 300., 400.,   0., 100., 100., 200.,
       200., 300., 300., 400.,   0., 100., 100., 200., 200., 300., 300.,
       400.,   0., 100., 100., 200., 200., 300., 300., 400.])

In [26]:
model.coor['y']

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 400., 400., 400., 400., 400., 400., 400., 400.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 400., 400., 400., 400., 400., 400., 400., 400.])

In [27]:
model.coor['z']

array([2000., 2001., 2001., 2002., 2002., 2003., 2003., 2004., 2000.,
       2001., 2001., 2002., 2002., 2003., 2003., 2004., 2000., 2001.,
       2001., 2002., 2002., 2003., 2003., 2004., 2000., 2001., 2001.,
       2002., 2002., 2003., 2003., 2004., 2010., 2011., 2011., 2012.,
       2012., 2013., 2013., 2014., 2010., 2011., 2011., 2012., 2012.,
       2013., 2013., 2014., 2010., 2011., 2011., 2012., 2012., 2013.,
       2013., 2014., 2010., 2011., 2011., 2012., 2012., 2013., 2013.,
       2014.])

In [23]:
model.retornar_vertices_celula(cx, 0, 0, 0)

array([  0., 100., 100.,   0.,   0., 100., 100.,   0.])

In [30]:
cx.shape

(64,)

In [43]:
cy

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 400., 400., 400., 400., 400., 400., 400., 400.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 400., 400., 400., 400., 400., 400., 400., 400.])

In [44]:
cz

array([2000., 2001., 2001., 2002., 2002., 2003., 2003., 2004., 2000.,
       2001., 2001., 2002., 2002., 2003., 2003., 2004., 2000., 2001.,
       2001., 2002., 2002., 2003., 2003., 2004., 2000., 2001., 2001.,
       2002., 2002., 2003., 2003., 2004., 2010., 2011., 2011., 2012.,
       2012., 2013., 2013., 2014., 2010., 2011., 2011., 2012., 2012.,
       2013., 2013., 2014., 2010., 2011., 2011., 2012., 2012., 2013.,
       2013., 2014., 2010., 2011., 2011., 2012., 2012., 2013., 2013.,
       2014.])

In [43]:
model.calculate_volumes()

Loading Volumes: 100%|██████████| 1000/1000 [00:00<00:00, 58855.86it/s]


In [44]:
model.volumes

array([[[14000., 13900., 14000., 13900., 14000., 13900., 14000., 14000.,
         13900., 14000.],
        [14100., 14000., 14000., 14000., 14000., 14100., 14000., 14000.,
         14000., 14000.],
        [14100., 14000., 14100., 14100., 14100., 14100., 14100., 14000.,
         14100., 14100.],
        [14100., 14100., 14200., 14100., 14200., 14100., 14100., 14200.,
         14100., 14100.],
        [14100., 14200., 14200., 14200., 14100., 14200., 14200., 14100.,
         14200., 14200.],
        [14200., 14200., 14200., 14200., 14200., 14200., 14100., 14200.,
         14200., 14200.],
        [14200., 14200., 14100., 14200., 14200., 14200., 14200., 14200.,
         14100., 14200.],
        [14100., 14200., 14100., 14200., 14200., 14100., 14200., 14100.,
         14200., 14200.],
        [14200., 14100., 14100., 14100., 14200., 14100., 14100., 14100.,
         14100., 14200.],
        [14000., 14100., 14100., 14100., 14000., 14100., 14100., 14100.,
         14000., 14100.]],

       [